000001*PROGMODE: (BATCH,MAIN),($DEF)                                    01000114
000002 IDENTIFICATION DIVISION.                                         01000145
000003**PDL*201407281625/CLONETEST1/03/PROGRAM CLONETEST1 ADS-60        01000178
000004*                                                                 01000180
000005*                          PROGRAM GENERATED BY ADS REL 60        01000181
000006*                                                                 01000182
000007 PROGRAM-ID.                 CLONETEST1.                          01000188
000008 AUTHOR.                     NOAUTHOR.                            01000190
000009 DATE-WRITTEN.               28 07 2014.                          01000191
000010 ENVIRONMENT DIVISION.                                            01000200
000011 CONFIGURATION SECTION.                                           01000201
000012 SOURCE-COMPUTER.            MICROFOCUS.                          01000205
000013 OBJECT-COMPUTER.            MICROFOCUS.                          01000206
000014 DATA DIVISION.                                                   01000232
000015 WORKING-STORAGE SECTION.                                         01000243
000016* ------------------------------------------------> WORK77 USER   01000245
000017* ------------------------------------------------> WORK01        01000248
000018 01  CLONETEST1-1.                                                03000019
000019     10 DX-CONSTANTS-NEW.                                         03000020
000020       15 DC-DELTA-REL   PIC S9(4) COMP-5 VALUE +60.              03000021
000021       15 DC-REL REDEFINES DC-DELTA-REL PIC S9(4) COMP-5.         03000022
000022     10 DX-CONSTANTS.                                             03000023
000023       15 DC-PROGID      PIC X(12) VALUE 'CLONETEST1'.            03000024
000024       15 DC-GENDATE     PIC X(12) VALUE '201407281625'.          03000025
000025       15 FILLER         PIC XX    VALUE SPACE.                   03000026
000026*                                                                 03000027
000027       15 DC-KEYANDSTAT  PIC S9(4) COMP-5 VALUE -3.               03000028
000028       15 DC-STATUS-SET  PIC S9(4) COMP-5 VALUE -2.               03000029
000029       15 DC-KEY-SET     PIC S9(4) COMP-5 VALUE -1.               03000030
000030*                                                                 03000031
000031       15 DC-START       PIC S9(4) COMP-5 VALUE +0.               03000032
000032       15 DC-KEYCHANGED  REDEFINES DC-START     PIC S9(4) COMP-5. 03000033
000033       15 DC-TURN-OFF    REDEFINES DC-START     PIC S9(4) COMP-5. 03000034
000034*                                                                 03000035
000035       15 DX-NF          PIC S9(4) COMP-5 VALUE +1.               03000036
000036       15 DX-OPEN        REDEFINES DX-NF        PIC S9(4) COMP-5. 03000037
000037       15 DC-NOTFOUND    REDEFINES DX-NF        PIC S9(4) COMP-5. 03000038
000038       15 DC-NOTOK       REDEFINES DX-NF        PIC S9(4) COMP-5. 03000039
000039       15 DC-TURN-ON     REDEFINES DX-NF        PIC S9(4) COMP-5. 03000040
000040       15 DC-BACK        REDEFINES DX-NF        PIC S9(4) COMP-5. 03000041
000041       15 DC-NO-COMMIT   REDEFINES DX-NF        PIC S9(4) COMP-5. 03000042
000042       15 DC-RESTART     REDEFINES DX-NF        PIC S9(4) COMP-5. 03000043
000043*                                                                 03000044
000044       15 DC-FOUND       PIC S9(4) COMP-5 VALUE +2.               03000045
000045       15 DC-OK          REDEFINES DC-FOUND     PIC S9(4) COMP-5. 03000046
000046       15 DC-OLD         REDEFINES DC-FOUND     PIC S9(4) COMP-5. 03000047
000047       15 DC-CHAIN       REDEFINES DC-FOUND     PIC S9(4) COMP-5. 03000048
000048       15 DC-COMMIT-TEMP REDEFINES DC-FOUND     PIC S9(4) COMP-5. 03000049
000049       15 DC-LEAVE-IT    REDEFINES DC-FOUND     PIC S9(4) COMP-5. 03000050
000050*                                                                 03000051
000051       15 DC-DEL         PIC S9(4) COMP-5 VALUE +3.               03000052
000052       15 DC-EOF         REDEFINES DC-DEL       PIC S9(4) COMP-5. 03000053
000053       15 DC-GOTO        REDEFINES DC-DEL       PIC S9(4) COMP-5. 03000054
000054       15 DC-COMMIT-PERM REDEFINES DC-DEL       PIC S9(4) COMP-5. 03000055
000055       15 DC-COMMIT      REDEFINES DC-DEL       PIC S9(4) COMP-5. 03000057
000056       15 DC-RETRY       REDEFINES DC-DEL       PIC S9(4) COMP-5. 03000063
000057*                                                                 03000064
000058       15 DX-CLOSE       PIC S9(4) COMP-5 VALUE +4.               03000065
000059       15 DC-INCOMPLETE  REDEFINES DX-CLOSE     PIC S9(4) COMP-5. 03000066
000060       15 DC-REPL        REDEFINES DX-CLOSE     PIC S9(4) COMP-5. 03000067
000061       15 DC-CALL        REDEFINES DX-CLOSE     PIC S9(4) COMP-5. 03000068
000062       15 DC-ROLLBACK    REDEFINES DX-CLOSE     PIC S9(4) COMP-5. 03000070
000063       15 DC-UNDO        REDEFINES DX-CLOSE     PIC S9(4) COMP-5. 03000071
000064       15 DC-OTHERPAGE   REDEFINES DX-CLOSE     PIC S9(4) COMP-5. 03000078
000065*                                                                 03000079
000066       15 DC-LOCKED      PIC S9(4) COMP-5 VALUE +5.               03000080
000067       15 DC-NEW         REDEFINES DC-LOCKED    PIC S9(4) COMP-5. 03000081
000068       15 DC-RETURN      REDEFINES DC-LOCKED    PIC S9(4) COMP-5. 03000082
000069       15 DC-ABEND       REDEFINES DC-LOCKED    PIC S9(4) COMP-5. 03000083
000070*                                                                 03000084
000071       15 DC-I-O-ERROR   PIC S9(4) COMP-5 VALUE +6.               03000085
000072       15 DC-STOP        REDEFINES DC-I-O-ERROR PIC S9(4) COMP-5. 03000086
000073*                                                                 03000087
000074       15 DC-DUPKEY      PIC S9(4) COMP-5 VALUE +7.               03000088
000075       15 DC-NEXT        REDEFINES DC-DUPKEY    PIC S9(4) COMP-5. 03000089
000076       15 DC-COPY        REDEFINES DC-DUPKEY    PIC S9(4) COMP-5. 03000090
000077*                                                                 03000091
000078       15 DC-READ-AGAIN  PIC S9(4) COMP-5 VALUE +8.               03000092
000079*                                                                 03000093
000080       15 DC-STORE       PIC S9(4) COMP-5 VALUE +9.               03000094
000081*                                                                 03000116
000082 01  DX-REC.                                                      03000117
000083     10 DX-TEXT          PIC X(20) VALUE SPACE.                   03000118
000084     10 DX-VALUE.                                                 03000119
000085       15 DX-VALUE1      PIC X(20) VALUE SPACE.                   03000120
000086       15 DX-VALUE2.                                              03000121
000087         20 DX-VALUE3    PIC X(32) VALUE SPACE.                   03000122
000088         20 DX-VALUEX.                                            03000123
000089            25 DX-VALUE9 PIC 9(8)  VALUE ZERO.                    03000124
000090 01    STATUS-PROGRAM PIC S9(4) COMP-5.                           03000142
000091 01    DCV-ERROR-SEVERITY PIC S9(4) COMP-5.                       03000143
000092 01    DCV-SC-NEXT    PIC S9(4) COMP-5 VALUE ZERO.                03000148
000093 01  DX-WORK-DATA.                                                01000250
000094     10 FILLER     PIC S9(8) COMP SYNC RIGHT.                     01000254
000095* ------------------------------------------------> WORK01 USER   01000256
000096 PROCEDURE DIVISION.                                              04000060
000097*                                      *========================* 01000279
000098* =====================================I   PROCEDURE DIVISION   I 01000280
000099*                                      *========================* 01000281
000100 DX-MAIN SECTION.                                                 01000290
000101 DX-PRO-PROG.                                                     PR-DELTA
000102     MOVE DC-OK TO STATUS-PROGRAM.                                03000161
000103     MOVE DC-TURN-OFF TO DCV-ERROR-SEVERITY.                      03000162
000104* ------------------------------------------------> FILE-OPEN     03000168
000105* ------------------------------------------------> O-PROG        01000293
000106* ------------------------------------------------> P-PROG        PR-DELTA
000107 TEST3.                                                           00000005
000108        MOVE 1 TO ABC-CLONETEST1-01.                              00000006
000109        MOVE 2 TO ABC-CLONETEST1-02.                              00000007
000110        MOVE 3 TO ABC-CLONETEST1-03.                              00000008
000111        MOVE 4 TO ABC-CLONETEST1-04.                              00000009
000112        MOVE 5 TO ABC-CLONETEST1-05.                              00000010
000113        MOVE 6 TO ABC-CLONETEST1-06.                              00000011
000114        MOVE 7 TO ABC-CLONETEST1-07.                              00000012
000115*                                                                 00000014
000116 TEST3.                                                           00000016
000117        MOVE 1 TO ABC-CLONETEST1-01.                              00000017
000118        MOVE 2 TO ABC-CLONETEST1-02.                              00000018
000119        MOVE 3 TO ABC-CLONETEST1-03.                              00000019
000120        MOVE 4 TO ABC-CLONETEST1-04.                              00000020
000121        MOVE 5 TO ABC-CLONETEST1-05.                              00000021
000122        MOVE 6 TO ABC-CLONETEST1-06.                              00000022
000123        MOVE 7 TO ABC-CLONETEST1-07.                              00000023
000124 DX-PRC-PROG.                                                     PR-DELTA
000125* ------------------------------------------------> C-PROG        PR-DELTA
000126                 EXIT.                                            PR-SCORE
000127 FILE-CLOSE.                                                      PR-DELTA
000128* ------------------------------------------------> FILE-CLOSE    01000295
000129                 EXIT.                                            PR-SCORE
000130 STOP-RUN.                                                        PR-DELTA
000131     STOP RUN.                                                    04000081
000132* ------------------------------------------------> R-PROG        01000297
000133 PUT-DX.                                                          01000302
000134     DISPLAY DX-REC.                                              01000303
000135 PUT-DX-EXIT. EXIT.                                               01000304
000136* ------------------------------------------------> FILE-ROUT     01000351
000137* ------------------------------------------------> BOTTOM        01000353
